# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_system/zynq_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system || ORIG_REF_NAME==zynq_system} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_processing_system7_0_1/zynq_system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_1 || ORIG_REF_NAME==zynq_system_processing_system7_0_1} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_ps7_0_axi_periph_1/zynq_system_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_ps7_0_axi_periph_1 || ORIG_REF_NAME==zynq_system_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_rst_ps7_0_100M_1/zynq_system_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_rst_ps7_0_100M_1 || ORIG_REF_NAME==zynq_system_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_fifo_reader_0_0/zynq_system_fifo_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_fifo_reader_0_0 || ORIG_REF_NAME==zynq_system_fifo_reader_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_regmap_0_0/zynq_system_axi_regmap_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_axi_regmap_0_0 || ORIG_REF_NAME==zynq_system_axi_regmap_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_fifo_adapter_0_0/zynq_system_fifo_adapter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_fifo_adapter_0_0 || ORIG_REF_NAME==zynq_system_fifo_adapter_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_auto_pc_0/zynq_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_0 || ORIG_REF_NAME==zynq_system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Matt/Documents/Vivado_Projects/MIDI_Interface/MIDI_Interface.gen/sources_1/bd/zynq_system/zynq_system_ooc.xdc
