# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Matt/Documents/Vivado_Projects/MIDI_Interface/fpga_synth/fpga_synth.srcs/sources_1/bd/dds/ip/dds_dds_compiler_0_1/dds_dds_compiler_0_1.xci
# IP: The module: 'dds_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matt/Documents/Vivado_Projects/MIDI_Interface/fpga_synth/fpga_synth.gen/sources_1/bd/dds/ip/dds_dds_compiler_0_1/dds_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Matt/Documents/Vivado_Projects/MIDI_Interface/fpga_synth/fpga_synth.srcs/sources_1/bd/dds/ip/dds_dds_compiler_0_1/dds_dds_compiler_0_1.xci
# IP: The module: 'dds_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matt/Documents/Vivado_Projects/MIDI_Interface/fpga_synth/fpga_synth.gen/sources_1/bd/dds/ip/dds_dds_compiler_0_1/dds_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
